import type {Metadata} from "next";
import ThemeRegistry from "@/components/theme-registry/ThemeRegistry.component";
import {CssBaseline} from "@mui/material";
import {Provider} from "@/utils/Providers";

export const metadata: Metadata = {
  title: "Between You & AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <CssBaseline />
          <Provider>
            {children}
          </Provider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
