import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "@/components/theme-registry/ThemeRegistry.component";


export const metadata: Metadata = {
  title: "Between You & AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeRegistry >
        <body>{children}</body>
      </ThemeRegistry>
    </html>
  );
}
