CREATE USER ga WITH PASSWORD 'ga';

DROP DATABASE IF EXISTS circle_test;
CREATE DATABASE circle_test;

GRANT ALL PRIVILEGES ON DATABASE circle_test TO ga;
GRANT CONNECT ON DATABASE circle_test TO ga;
\connect circle_test
GRANT ALL ON SCHEMA public TO ga;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ga;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ga;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ga;
-- GA = Github Actions